version: "3"

services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"

  server:
    build: ./server
    ports:
      - "3001:3001"

    depends_on:
      - mongodb
    environment:
      DATABASE_URL: "mongodb://host.docker.internal:27017/projects"

  client:
    build: ./client

    ports:
      - "3000:3000"
    volumes:
      - ./client/src:/app/src

    depends_on:
      - server