# Generated by Django 4.0.5 on 2023-02-06 07:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomCompanyModel',
            fields=[
                ('company_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('company_readable_id', models.CharField(blank=20, max_length=20, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=20)),
                ('account_funds', models.CharField(default=1000, max_length=20)),
                ('owner', models.CharField(default='anon', max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company',
                'permissions': [('change_company_name', 'Can change the company name'), ('withdraw_funds', 'Can withdraw funds from the company'), ('can_delete_company', 'Can delete company')],
            },
        ),
        migrations.CreateModel(
            name='CustomUserModel',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('userId', models.CharField(default=uuid.uuid4, max_length=50, primary_key=True, serialize=False)),
                ('username', models.CharField(default=False, max_length=20, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('role', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'owner'), (2, 'company_admin'), (3, 'user')], null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_company_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('funds', models.PositiveIntegerField(default=1000)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.customcompanymodel')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Custom User',
            },
        ),
    ]
