# Generated by Django 4.0.5 on 2023-02-06 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='role',
            field=models.CharField(blank=True, choices=[('owner', 'owner'), ('company_admin', 'company_admin'), ('user', 'user')], max_length=13, null=True),
        ),
    ]
