POST http://localhost:3000/api/user/register
content-type: application/json

{
    "name": "david",
    "email": "test205@gmail.com",
    "password": "szcxzcxzd"
}

###
GET http://localhost:3000/api/user